insert into public.exercises (id, name, muscle_primary, muscle_secondary, equipment, difficulty, movement_pattern, cues, substitutions, tags, created_at)
values
(gen_random_uuid(), 'Barbell Bench Press', 'Chest', ARRAY['Triceps','Front Delts']::text[], 'Barbell', 'intermediate', 'Horizontal Push', 'Shoulder blades pinned back and down. Bar to lower chest, elbows about 45 degrees from your ribs.', '{}'::text[], ARRAY['Horizontal Push','Barbell']::text[], now()),
(gen_random_uuid(), 'Incline Barbell Bench Press', 'Upper Chest', ARRAY['Front Delts','Triceps']::text[], 'Barbell', 'intermediate', 'Horizontal Push', 'Bench at 30 degrees. Any higher and it turns into a shoulder press.', '{}'::text[], ARRAY['Horizontal Push','Barbell']::text[], now()),
(gen_random_uuid(), 'Decline Barbell Bench Press', 'Lower Chest', ARRAY['Triceps']::text[], 'Barbell', 'intermediate', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Barbell']::text[], now()),
(gen_random_uuid(), 'Close Grip Bench Press', 'Triceps', ARRAY['Chest','Front Delts']::text[], 'Barbell', 'intermediate', 'Horizontal Push', 'Hands shoulder width, elbows tucked tight. This is a triceps movement that happens to use a bench.', '{}'::text[], ARRAY['Horizontal Push','Barbell']::text[], now()),
(gen_random_uuid(), 'Flat Dumbbell Press', 'Chest', ARRAY['Triceps','Front Delts']::text[], 'Dumbbell', 'beginner', 'Horizontal Push', 'Let the dumbbells travel slightly toward each other at the top without banging them together.', '{}'::text[], ARRAY['Horizontal Push','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Incline Dumbbell Press', 'Upper Chest', ARRAY['Front Delts','Triceps']::text[], 'Dumbbell', 'beginner', 'Horizontal Push', 'Drive through the chest, not the shoulders. Stop just short of lockout to keep tension.', '{}'::text[], ARRAY['Horizontal Push','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Decline Dumbbell Press', 'Lower Chest', ARRAY['Triceps']::text[], 'Dumbbell', 'intermediate', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Neutral Grip Dumbbell Press', 'Chest', ARRAY['Triceps','Front Delts']::text[], 'Dumbbell', 'beginner', 'Horizontal Push', 'Palms facing each other is the friendliest version if your shoulders get cranky.', '{}'::text[], ARRAY['Horizontal Push','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Machine Chest Press', 'Chest', ARRAY['Triceps','Front Delts']::text[], 'Machine', 'beginner', 'Horizontal Push', 'Set the seat so the handles line up with mid chest.', '{}'::text[], ARRAY['Horizontal Push','Machine']::text[], now()),
(gen_random_uuid(), 'Incline Machine Press', 'Upper Chest', ARRAY['Front Delts','Triceps']::text[], 'Machine', 'beginner', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Machine']::text[], now()),
(gen_random_uuid(), 'Smith Machine Bench Press', 'Chest', ARRAY['Triceps','Front Delts']::text[], 'Smith Machine', 'beginner', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Smith Machine']::text[], now()),
(gen_random_uuid(), 'Smith Machine Incline Press', 'Upper Chest', ARRAY['Front Delts','Triceps']::text[], 'Smith Machine', 'beginner', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Smith Machine']::text[], now()),
(gen_random_uuid(), 'Dumbbell Fly', 'Chest', '{}'::text[], 'Dumbbell', 'intermediate', 'Horizontal Push', 'Soft elbow the whole way. Think about hugging a barrel, not pressing.', '{}'::text[], ARRAY['Horizontal Push','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Incline Dumbbell Fly', 'Upper Chest', '{}'::text[], 'Dumbbell', 'intermediate', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Cable Fly (Mid)', 'Chest', '{}'::text[], 'Cable', 'beginner', 'Horizontal Push', 'Squeeze for a full second where your hands meet. That''s where the work is.', '{}'::text[], ARRAY['Horizontal Push','Cable']::text[], now()),
(gen_random_uuid(), 'Cable Fly (High to Low)', 'Lower Chest', '{}'::text[], 'Cable', 'beginner', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Cable']::text[], now()),
(gen_random_uuid(), 'Cable Fly (Low to High)', 'Upper Chest', '{}'::text[], 'Cable', 'beginner', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Cable']::text[], now()),
(gen_random_uuid(), 'Pec Deck', 'Chest', '{}'::text[], 'Machine', 'beginner', 'Horizontal Push', 'Great finisher. Chase the stretch on the way out, not just the squeeze.', '{}'::text[], ARRAY['Horizontal Push','Machine']::text[], now()),
(gen_random_uuid(), 'Push Up', 'Chest', ARRAY['Triceps','Core','Front Delts']::text[], 'Bodyweight', 'beginner', 'Horizontal Push', 'Body in one straight line. Hips sagging means the core quit before the chest did.', '{}'::text[], ARRAY['Horizontal Push','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Incline Push Up', 'Chest', ARRAY['Triceps']::text[], 'Bodyweight', 'beginner', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Decline Push Up', 'Upper Chest', ARRAY['Front Delts','Triceps']::text[], 'Bodyweight', 'intermediate', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Deficit Push Up', 'Chest', ARRAY['Triceps']::text[], 'Bodyweight', 'intermediate', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Diamond Push Up', 'Triceps', ARRAY['Chest']::text[], 'Bodyweight', 'intermediate', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Chest Dip', 'Lower Chest', ARRAY['Triceps','Front Delts']::text[], 'Bodyweight', 'intermediate', 'Vertical Push', 'Lean the torso forward to bias the chest. Staying upright turns it into triceps.', '{}'::text[], ARRAY['Vertical Push','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Machine Assisted Dip', 'Lower Chest', ARRAY['Triceps']::text[], 'Machine', 'beginner', 'Vertical Push', NULL, '{}'::text[], ARRAY['Vertical Push','Machine']::text[], now()),
(gen_random_uuid(), 'Weighted Chest Dip', 'Lower Chest', ARRAY['Triceps']::text[], 'Bodyweight', 'advanced', 'Vertical Push', NULL, '{}'::text[], ARRAY['Vertical Push','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Svend Press', 'Chest', '{}'::text[], 'Plate', 'beginner', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Plate']::text[], now()),
(gen_random_uuid(), 'Landmine Press', 'Upper Chest', ARRAY['Front Delts','Triceps']::text[], 'Landmine', 'beginner', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Landmine']::text[], now()),
(gen_random_uuid(), 'Floor Press', 'Chest', ARRAY['Triceps']::text[], 'Barbell', 'intermediate', 'Horizontal Push', 'Triceps get hammered here and the floor protects your shoulders at the bottom.', '{}'::text[], ARRAY['Horizontal Push','Barbell']::text[], now()),
(gen_random_uuid(), 'Dumbbell Floor Press', 'Chest', ARRAY['Triceps']::text[], 'Dumbbell', 'beginner', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Guillotine Press', 'Upper Chest', ARRAY['Front Delts']::text[], 'Barbell', 'advanced', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Barbell']::text[], now()),
(gen_random_uuid(), 'Plate Pinch Press', 'Chest', '{}'::text[], 'Plate', 'beginner', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Plate']::text[], now()),
(gen_random_uuid(), 'Banded Push Up', 'Chest', ARRAY['Triceps']::text[], 'Band', 'intermediate', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Band']::text[], now()),
(gen_random_uuid(), 'Single Arm Cable Press', 'Chest', ARRAY['Core','Triceps']::text[], 'Cable', 'intermediate', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Cable']::text[], now()),
(gen_random_uuid(), 'Hammer Strength Chest Press', 'Chest', ARRAY['Triceps','Front Delts']::text[], 'Machine', 'beginner', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Machine']::text[], now()),
(gen_random_uuid(), 'Conventional Deadlift', 'Back', ARRAY['Hamstrings','Glutes','Traps','Core']::text[], 'Barbell', 'advanced', 'Hinge', 'Bar stays against the legs the whole way. Push the floor away instead of yanking the bar up.', '{}'::text[], ARRAY['Hinge','Barbell']::text[], now()),
(gen_random_uuid(), 'Sumo Deadlift', 'Glutes', ARRAY['Quads','Back','Hamstrings']::text[], 'Barbell', 'advanced', 'Hinge', 'Wide stance, knees tracking out over the toes. Chest up before the bar moves.', '{}'::text[], ARRAY['Hinge','Barbell']::text[], now()),
(gen_random_uuid(), 'Trap Bar Deadlift', 'Back', ARRAY['Quads','Glutes','Hamstrings']::text[], 'Trap Bar', 'intermediate', 'Hinge', 'Easiest deadlift to learn and the kindest on the lower back.', '{}'::text[], ARRAY['Hinge','Trap Bar']::text[], now()),
(gen_random_uuid(), 'Deficit Deadlift', 'Back', ARRAY['Hamstrings','Glutes']::text[], 'Barbell', 'advanced', 'Hinge', NULL, '{}'::text[], ARRAY['Hinge','Barbell']::text[], now()),
(gen_random_uuid(), 'Rack Pull', 'Back', ARRAY['Traps','Glutes']::text[], 'Barbell', 'intermediate', 'Hinge', NULL, '{}'::text[], ARRAY['Hinge','Barbell']::text[], now()),
(gen_random_uuid(), 'Barbell Bent Over Row', 'Back', ARRAY['Biceps','Rear Delts']::text[], 'Barbell', 'intermediate', 'Horizontal Pull', 'Torso around 45 degrees, bar to the belly button. Pull with the elbows, not the hands.', '{}'::text[], ARRAY['Horizontal Pull','Barbell']::text[], now()),
(gen_random_uuid(), 'Pendlay Row', 'Back', ARRAY['Biceps','Rear Delts']::text[], 'Barbell', 'advanced', 'Horizontal Pull', 'Bar resets on the floor every rep. No momentum available.', '{}'::text[], ARRAY['Horizontal Pull','Barbell']::text[], now()),
(gen_random_uuid(), 'Yates Row', 'Back', ARRAY['Biceps']::text[], 'Barbell', 'intermediate', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Barbell']::text[], now()),
(gen_random_uuid(), 'T-Bar Row', 'Back', ARRAY['Biceps','Rear Delts']::text[], 'Landmine', 'intermediate', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Landmine']::text[], now()),
(gen_random_uuid(), 'Chest Supported Row', 'Back', ARRAY['Rear Delts','Biceps']::text[], 'Machine', 'beginner', 'Horizontal Pull', 'Chest pad takes the lower back out entirely, so you can go heavy without cheating.', '{}'::text[], ARRAY['Horizontal Pull','Machine']::text[], now()),
(gen_random_uuid(), 'Seal Row', 'Back', ARRAY['Rear Delts','Biceps']::text[], 'Barbell', 'intermediate', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Barbell']::text[], now()),
(gen_random_uuid(), 'Single Arm Dumbbell Row', 'Back', ARRAY['Biceps','Rear Delts']::text[], 'Dumbbell', 'beginner', 'Horizontal Pull', 'Pull the dumbbell to your hip, not your armpit. Full stretch at the bottom.', '{}'::text[], ARRAY['Horizontal Pull','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Dumbbell Bent Over Row', 'Back', ARRAY['Biceps']::text[], 'Dumbbell', 'beginner', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Seated Cable Row', 'Back', ARRAY['Biceps','Rear Delts']::text[], 'Cable', 'beginner', 'Horizontal Pull', 'Let the shoulder blades come forward at the stretch, then pull them together hard.', '{}'::text[], ARRAY['Horizontal Pull','Cable']::text[], now()),
(gen_random_uuid(), 'Wide Grip Seated Row', 'Back', ARRAY['Rear Delts']::text[], 'Cable', 'beginner', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Cable']::text[], now()),
(gen_random_uuid(), 'Single Arm Cable Row', 'Back', ARRAY['Biceps']::text[], 'Cable', 'beginner', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Cable']::text[], now()),
(gen_random_uuid(), 'Machine Row', 'Back', ARRAY['Biceps']::text[], 'Machine', 'beginner', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Machine']::text[], now()),
(gen_random_uuid(), 'Hammer Strength Row', 'Back', ARRAY['Biceps','Rear Delts']::text[], 'Machine', 'beginner', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Machine']::text[], now()),
(gen_random_uuid(), 'Pull Up', 'Back', ARRAY['Biceps','Rear Delts']::text[], 'Bodyweight', 'intermediate', 'Vertical Pull', 'Full hang at the bottom. Chest to the bar, not chin over it, if you can manage it.', '{}'::text[], ARRAY['Vertical Pull','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Chin Up', 'Back', ARRAY['Biceps']::text[], 'Bodyweight', 'intermediate', 'Vertical Pull', 'Underhand grip lets the biceps help, so most people can do more of these than pull ups.', '{}'::text[], ARRAY['Vertical Pull','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Neutral Grip Pull Up', 'Back', ARRAY['Biceps']::text[], 'Bodyweight', 'intermediate', 'Vertical Pull', NULL, '{}'::text[], ARRAY['Vertical Pull','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Weighted Pull Up', 'Back', ARRAY['Biceps']::text[], 'Bodyweight', 'advanced', 'Vertical Pull', NULL, '{}'::text[], ARRAY['Vertical Pull','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Assisted Pull Up', 'Back', ARRAY['Biceps']::text[], 'Machine', 'beginner', 'Vertical Pull', NULL, '{}'::text[], ARRAY['Vertical Pull','Machine']::text[], now()),
(gen_random_uuid(), 'Lat Pulldown', 'Back', ARRAY['Biceps']::text[], 'Cable', 'beginner', 'Vertical Pull', 'Drive the elbows down toward your back pockets. Don''t lean back past about 20 degrees.', '{}'::text[], ARRAY['Vertical Pull','Cable']::text[], now()),
(gen_random_uuid(), 'Close Grip Lat Pulldown', 'Back', ARRAY['Biceps']::text[], 'Cable', 'beginner', 'Vertical Pull', NULL, '{}'::text[], ARRAY['Vertical Pull','Cable']::text[], now()),
(gen_random_uuid(), 'Wide Grip Lat Pulldown', 'Back', ARRAY['Rear Delts']::text[], 'Cable', 'beginner', 'Vertical Pull', NULL, '{}'::text[], ARRAY['Vertical Pull','Cable']::text[], now()),
(gen_random_uuid(), 'Reverse Grip Lat Pulldown', 'Back', ARRAY['Biceps']::text[], 'Cable', 'beginner', 'Vertical Pull', NULL, '{}'::text[], ARRAY['Vertical Pull','Cable']::text[], now()),
(gen_random_uuid(), 'Single Arm Lat Pulldown', 'Back', ARRAY['Biceps']::text[], 'Cable', 'intermediate', 'Vertical Pull', NULL, '{}'::text[], ARRAY['Vertical Pull','Cable']::text[], now()),
(gen_random_uuid(), 'Straight Arm Pulldown', 'Lats', '{}'::text[], 'Cable', 'beginner', 'Vertical Pull', 'Arms stay locked. This is a lat movement, not a triceps one.', '{}'::text[], ARRAY['Vertical Pull','Cable']::text[], now()),
(gen_random_uuid(), 'Cable Pullover', 'Lats', '{}'::text[], 'Cable', 'intermediate', 'Vertical Pull', NULL, '{}'::text[], ARRAY['Vertical Pull','Cable']::text[], now()),
(gen_random_uuid(), 'Dumbbell Pullover', 'Lats', ARRAY['Chest']::text[], 'Dumbbell', 'intermediate', 'Vertical Pull', NULL, '{}'::text[], ARRAY['Vertical Pull','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Inverted Row', 'Back', ARRAY['Biceps','Rear Delts']::text[], 'Bodyweight', 'beginner', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Meadows Row', 'Back', ARRAY['Rear Delts','Biceps']::text[], 'Landmine', 'advanced', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Landmine']::text[], now()),
(gen_random_uuid(), 'Kroc Row', 'Back', ARRAY['Biceps','Traps']::text[], 'Dumbbell', 'advanced', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Smith Machine Row', 'Back', ARRAY['Biceps']::text[], 'Smith Machine', 'beginner', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Smith Machine']::text[], now()),
(gen_random_uuid(), 'Back Extension', 'Lower Back', ARRAY['Glutes','Hamstrings']::text[], 'Machine', 'beginner', 'Hinge', 'Round up one vertebra at a time. Don''t hyperextend at the top.', '{}'::text[], ARRAY['Hinge','Machine']::text[], now()),
(gen_random_uuid(), '45 Degree Hyperextension', 'Lower Back', ARRAY['Glutes','Hamstrings']::text[], 'Machine', 'beginner', 'Hinge', NULL, '{}'::text[], ARRAY['Hinge','Machine']::text[], now()),
(gen_random_uuid(), 'Good Morning', 'Hamstrings', ARRAY['Lower Back','Glutes']::text[], 'Barbell', 'advanced', 'Hinge', NULL, '{}'::text[], ARRAY['Hinge','Barbell']::text[], now()),
(gen_random_uuid(), 'Rope Face Pull', 'Rear Delts', ARRAY['Traps','Rotator Cuff']::text[], 'Cable', 'beginner', 'Horizontal Pull', 'Pull to the forehead and rotate the pinkies back. Best shoulder health movement there is.', '{}'::text[], ARRAY['Horizontal Pull','Cable']::text[], now()),
(gen_random_uuid(), 'Band Pull Apart', 'Rear Delts', ARRAY['Traps']::text[], 'Band', 'beginner', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Band']::text[], now()),
(gen_random_uuid(), 'Overhead Barbell Press', 'Shoulders', ARRAY['Triceps','Core']::text[], 'Barbell', 'intermediate', 'Vertical Push', 'Squeeze the glutes so you don''t press with your lower back. Head moves through at the top.', '{}'::text[], ARRAY['Vertical Push','Barbell']::text[], now()),
(gen_random_uuid(), 'Seated Barbell Press', 'Shoulders', ARRAY['Triceps']::text[], 'Barbell', 'intermediate', 'Vertical Push', NULL, '{}'::text[], ARRAY['Vertical Push','Barbell']::text[], now()),
(gen_random_uuid(), 'Push Press', 'Shoulders', ARRAY['Triceps','Quads']::text[], 'Barbell', 'advanced', 'Vertical Push', NULL, '{}'::text[], ARRAY['Vertical Push','Barbell']::text[], now()),
(gen_random_uuid(), 'Seated Dumbbell Shoulder Press', 'Shoulders', ARRAY['Triceps']::text[], 'Dumbbell', 'beginner', 'Vertical Push', 'Stop just short of locking out to keep the delts loaded.', '{}'::text[], ARRAY['Vertical Push','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Standing Dumbbell Press', 'Shoulders', ARRAY['Triceps','Core']::text[], 'Dumbbell', 'intermediate', 'Vertical Push', NULL, '{}'::text[], ARRAY['Vertical Push','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Arnold Press', 'Shoulders', ARRAY['Triceps']::text[], 'Dumbbell', 'intermediate', 'Vertical Push', 'The rotation hits front and side delts in one movement. Go lighter than a normal press.', '{}'::text[], ARRAY['Vertical Push','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Machine Shoulder Press', 'Shoulders', ARRAY['Triceps']::text[], 'Machine', 'beginner', 'Vertical Push', NULL, '{}'::text[], ARRAY['Vertical Push','Machine']::text[], now()),
(gen_random_uuid(), 'Smith Machine Shoulder Press', 'Shoulders', ARRAY['Triceps']::text[], 'Smith Machine', 'beginner', 'Vertical Push', NULL, '{}'::text[], ARRAY['Vertical Push','Smith Machine']::text[], now()),
(gen_random_uuid(), 'Landmine Shoulder Press', 'Shoulders', ARRAY['Triceps','Core']::text[], 'Landmine', 'beginner', 'Vertical Push', NULL, '{}'::text[], ARRAY['Vertical Push','Landmine']::text[], now()),
(gen_random_uuid(), 'Z Press', 'Shoulders', ARRAY['Core','Triceps']::text[], 'Barbell', 'advanced', 'Vertical Push', NULL, '{}'::text[], ARRAY['Vertical Push','Barbell']::text[], now()),
(gen_random_uuid(), 'Dumbbell Lateral Raise', 'Side Delts', '{}'::text[], 'Dumbbell', 'beginner', 'Isolation', 'Lead with the elbows, thumbs slightly down. Stop at shoulder height.', '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Cable Lateral Raise', 'Side Delts', '{}'::text[], 'Cable', 'beginner', 'Isolation', 'Cable keeps tension at the bottom where dumbbells lose it.', '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Machine Lateral Raise', 'Side Delts', '{}'::text[], 'Machine', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Leaning Cable Lateral Raise', 'Side Delts', '{}'::text[], 'Cable', 'intermediate', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Seated Dumbbell Lateral Raise', 'Side Delts', '{}'::text[], 'Dumbbell', 'beginner', 'Isolation', 'Sitting kills the leg drive people cheat with.', '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Lu Raise', 'Side Delts', ARRAY['Traps']::text[], 'Dumbbell', 'intermediate', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Front Raise', 'Front Delts', '{}'::text[], 'Dumbbell', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Cable Front Raise', 'Front Delts', '{}'::text[], 'Cable', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Plate Front Raise', 'Front Delts', '{}'::text[], 'Plate', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Plate']::text[], now()),
(gen_random_uuid(), 'Rear Delt Fly', 'Rear Delts', ARRAY['Traps']::text[], 'Dumbbell', 'beginner', 'Isolation', 'Hinge over and think about pulling the arms apart, not lifting them up.', '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Reverse Pec Deck', 'Rear Delts', ARRAY['Traps']::text[], 'Machine', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Cable Rear Delt Fly', 'Rear Delts', '{}'::text[], 'Cable', 'intermediate', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Bent Over Dumbbell Rear Delt Fly', 'Rear Delts', ARRAY['Traps']::text[], 'Dumbbell', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Upright Row', 'Side Delts', ARRAY['Traps','Biceps']::text[], 'Barbell', 'intermediate', 'Vertical Pull', 'Keep it to chest height. Higher than that is where shoulders get pinched.', '{}'::text[], ARRAY['Vertical Pull','Barbell']::text[], now()),
(gen_random_uuid(), 'Cable Upright Row', 'Side Delts', ARRAY['Traps']::text[], 'Cable', 'beginner', 'Vertical Pull', NULL, '{}'::text[], ARRAY['Vertical Pull','Cable']::text[], now()),
(gen_random_uuid(), 'Barbell Shrug', 'Traps', '{}'::text[], 'Barbell', 'beginner', 'Isolation', 'Straight up and down. Rolling the shoulders does nothing extra.', '{}'::text[], ARRAY['Isolation','Barbell']::text[], now()),
(gen_random_uuid(), 'Dumbbell Shrug', 'Traps', '{}'::text[], 'Dumbbell', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Trap Bar Shrug', 'Traps', '{}'::text[], 'Trap Bar', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Trap Bar']::text[], now()),
(gen_random_uuid(), 'Cable Shrug', 'Traps', '{}'::text[], 'Cable', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Machine Shrug', 'Traps', '{}'::text[], 'Machine', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Y Raise', 'Rear Delts', ARRAY['Traps']::text[], 'Dumbbell', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Cuban Press', 'Rotator Cuff', ARRAY['Shoulders']::text[], 'Dumbbell', 'intermediate', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Cable External Rotation', 'Rotator Cuff', '{}'::text[], 'Cable', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Band External Rotation', 'Rotator Cuff', '{}'::text[], 'Band', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Band']::text[], now()),
(gen_random_uuid(), 'Pike Push Up', 'Shoulders', ARRAY['Triceps']::text[], 'Bodyweight', 'intermediate', 'Vertical Push', NULL, '{}'::text[], ARRAY['Vertical Push','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Handstand Push Up', 'Shoulders', ARRAY['Triceps','Core']::text[], 'Bodyweight', 'advanced', 'Vertical Push', NULL, '{}'::text[], ARRAY['Vertical Push','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Barbell Curl', 'Biceps', ARRAY['Forearms']::text[], 'Barbell', 'beginner', 'Isolation', 'Elbows pinned to your sides. If they drift forward the front delts took over.', '{}'::text[], ARRAY['Isolation','Barbell']::text[], now()),
(gen_random_uuid(), 'EZ Bar Curl', 'Biceps', ARRAY['Forearms']::text[], 'Barbell', 'beginner', 'Isolation', 'Angled grip is easier on the wrists than a straight bar.', '{}'::text[], ARRAY['Isolation','Barbell']::text[], now()),
(gen_random_uuid(), 'Dumbbell Curl', 'Biceps', ARRAY['Forearms']::text[], 'Dumbbell', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Alternating Dumbbell Curl', 'Biceps', ARRAY['Forearms']::text[], 'Dumbbell', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Hammer Curl', 'Biceps', ARRAY['Forearms','Brachialis']::text[], 'Dumbbell', 'beginner', 'Isolation', 'Neutral grip builds the brachialis, which is what pushes the bicep up and out.', '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Cross Body Hammer Curl', 'Brachialis', ARRAY['Biceps']::text[], 'Dumbbell', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Incline Dumbbell Curl', 'Biceps', '{}'::text[], 'Dumbbell', 'intermediate', 'Isolation', 'Arms hanging behind the body gives the longest stretch on the long head.', '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Preacher Curl', 'Biceps', '{}'::text[], 'Barbell', 'beginner', 'Isolation', 'Arm locked on the pad means zero swing. Great when the lower back is fried.', '{}'::text[], ARRAY['Isolation','Barbell']::text[], now()),
(gen_random_uuid(), 'Dumbbell Preacher Curl', 'Biceps', '{}'::text[], 'Dumbbell', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Machine Preacher Curl', 'Biceps', '{}'::text[], 'Machine', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Cable Curl', 'Biceps', '{}'::text[], 'Cable', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Cable Rope Hammer Curl', 'Biceps', ARRAY['Forearms']::text[], 'Cable', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Bayesian Cable Curl', 'Biceps', '{}'::text[], 'Cable', 'intermediate', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Concentration Curl', 'Biceps', '{}'::text[], 'Dumbbell', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Spider Curl', 'Biceps', '{}'::text[], 'Dumbbell', 'intermediate', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Reverse Curl', 'Forearms', ARRAY['Biceps']::text[], 'Barbell', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Barbell']::text[], now()),
(gen_random_uuid(), 'Zottman Curl', 'Biceps', ARRAY['Forearms']::text[], 'Dumbbell', 'intermediate', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), '21s', 'Biceps', '{}'::text[], 'Barbell', 'intermediate', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Barbell']::text[], now()),
(gen_random_uuid(), 'Drag Curl', 'Biceps', '{}'::text[], 'Barbell', 'intermediate', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Barbell']::text[], now()),
(gen_random_uuid(), 'Machine Bicep Curl', 'Biceps', '{}'::text[], 'Machine', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Tricep Pushdown (Bar)', 'Triceps', '{}'::text[], 'Cable', 'beginner', 'Isolation', 'Elbows glued to your ribs. Only the forearms move.', '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Tricep Pushdown (Rope)', 'Triceps', '{}'::text[], 'Cable', 'beginner', 'Isolation', 'Spread the rope apart at the bottom for the extra squeeze.', '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Overhead Cable Tricep Extension', 'Triceps', '{}'::text[], 'Cable', 'beginner', 'Isolation', 'Overhead position stretches the long head, which most people never train.', '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Overhead Dumbbell Extension', 'Triceps', '{}'::text[], 'Dumbbell', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Skullcrusher', 'Triceps', '{}'::text[], 'Barbell', 'intermediate', 'Isolation', 'Lower to the forehead or just behind it. Elbows stay pointed at the ceiling.', '{}'::text[], ARRAY['Isolation','Barbell']::text[], now()),
(gen_random_uuid(), 'Dumbbell Skullcrusher', 'Triceps', '{}'::text[], 'Dumbbell', 'intermediate', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'JM Press', 'Triceps', ARRAY['Chest']::text[], 'Barbell', 'advanced', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Barbell']::text[], now()),
(gen_random_uuid(), 'Tricep Dip', 'Triceps', ARRAY['Chest']::text[], 'Bodyweight', 'intermediate', 'Vertical Push', 'Stay upright to keep it on the triceps.', '{}'::text[], ARRAY['Vertical Push','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Bench Dip', 'Triceps', '{}'::text[], 'Bodyweight', 'beginner', 'Vertical Push', NULL, '{}'::text[], ARRAY['Vertical Push','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Machine Tricep Extension', 'Triceps', '{}'::text[], 'Machine', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Single Arm Cable Kickback', 'Triceps', '{}'::text[], 'Cable', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Dumbbell Kickback', 'Triceps', '{}'::text[], 'Dumbbell', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Cable Cross Body Extension', 'Triceps', '{}'::text[], 'Cable', 'intermediate', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Wrist Curl', 'Forearms', '{}'::text[], 'Dumbbell', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Reverse Wrist Curl', 'Forearms', '{}'::text[], 'Dumbbell', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Farmer Carry', 'Forearms', ARRAY['Traps','Core']::text[], 'Dumbbell', 'beginner', 'Carry', 'Stand tall, don''t lean. Grip usually gives out before anything else.', '{}'::text[], ARRAY['Carry','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Plate Pinch Hold', 'Forearms', '{}'::text[], 'Plate', 'beginner', 'Carry', NULL, '{}'::text[], ARRAY['Carry','Plate']::text[], now()),
(gen_random_uuid(), 'Dead Hang', 'Forearms', ARRAY['Lats']::text[], 'Bodyweight', 'beginner', 'Carry', NULL, '{}'::text[], ARRAY['Carry','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Behind Back Barbell Wrist Curl', 'Forearms', '{}'::text[], 'Barbell', 'intermediate', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Barbell']::text[], now()),
(gen_random_uuid(), 'Back Squat', 'Quads', ARRAY['Glutes','Hamstrings','Core']::text[], 'Barbell', 'intermediate', 'Squat', 'Break at the hips and knees together. Knees track over the toes, chest stays proud.', '{}'::text[], ARRAY['Squat','Barbell']::text[], now()),
(gen_random_uuid(), 'Front Squat', 'Quads', ARRAY['Glutes','Core']::text[], 'Barbell', 'advanced', 'Squat', 'Elbows high. The second they drop the bar rolls forward.', '{}'::text[], ARRAY['Squat','Barbell']::text[], now()),
(gen_random_uuid(), 'High Bar Squat', 'Quads', ARRAY['Glutes']::text[], 'Barbell', 'intermediate', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Barbell']::text[], now()),
(gen_random_uuid(), 'Low Bar Squat', 'Glutes', ARRAY['Quads','Hamstrings']::text[], 'Barbell', 'advanced', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Barbell']::text[], now()),
(gen_random_uuid(), 'Box Squat', 'Glutes', ARRAY['Quads']::text[], 'Barbell', 'intermediate', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Barbell']::text[], now()),
(gen_random_uuid(), 'Pause Squat', 'Quads', ARRAY['Glutes']::text[], 'Barbell', 'advanced', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Barbell']::text[], now()),
(gen_random_uuid(), 'Goblet Squat', 'Quads', ARRAY['Glutes','Core']::text[], 'Dumbbell', 'beginner', 'Squat', 'Best squat to learn with. The weight in front keeps you upright automatically.', '{}'::text[], ARRAY['Squat','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Smith Machine Squat', 'Quads', ARRAY['Glutes']::text[], 'Smith Machine', 'beginner', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Smith Machine']::text[], now()),
(gen_random_uuid(), 'Hack Squat', 'Quads', ARRAY['Glutes']::text[], 'Machine', 'intermediate', 'Squat', 'Feet lower on the platform for more quad, higher for more glute.', '{}'::text[], ARRAY['Squat','Machine']::text[], now()),
(gen_random_uuid(), 'Pendulum Squat', 'Quads', ARRAY['Glutes']::text[], 'Machine', 'intermediate', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Machine']::text[], now()),
(gen_random_uuid(), 'Belt Squat', 'Quads', ARRAY['Glutes']::text[], 'Machine', 'intermediate', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Machine']::text[], now()),
(gen_random_uuid(), 'Leg Press', 'Quads', ARRAY['Glutes','Hamstrings']::text[], 'Machine', 'beginner', 'Squat', 'Don''t let the lower back round off the pad at the bottom. That''s where people get hurt.', '{}'::text[], ARRAY['Squat','Machine']::text[], now()),
(gen_random_uuid(), 'Single Leg Press', 'Quads', ARRAY['Glutes']::text[], 'Machine', 'intermediate', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Machine']::text[], now()),
(gen_random_uuid(), 'Bulgarian Split Squat', 'Quads', ARRAY['Glutes','Hamstrings']::text[], 'Dumbbell', 'intermediate', 'Lunge', 'Front foot far enough forward that the knee stays over the mid foot. Brutal and worth it.', '{}'::text[], ARRAY['Lunge','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Walking Lunge', 'Quads', ARRAY['Glutes','Hamstrings']::text[], 'Dumbbell', 'beginner', 'Lunge', NULL, '{}'::text[], ARRAY['Lunge','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Reverse Lunge', 'Glutes', ARRAY['Quads','Hamstrings']::text[], 'Dumbbell', 'beginner', 'Lunge', 'Stepping back is easier on the knees than stepping forward.', '{}'::text[], ARRAY['Lunge','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Forward Lunge', 'Quads', ARRAY['Glutes']::text[], 'Dumbbell', 'beginner', 'Lunge', NULL, '{}'::text[], ARRAY['Lunge','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Curtsy Lunge', 'Glutes', ARRAY['Quads']::text[], 'Dumbbell', 'intermediate', 'Lunge', NULL, '{}'::text[], ARRAY['Lunge','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Lateral Lunge', 'Adductors', ARRAY['Quads','Glutes']::text[], 'Dumbbell', 'intermediate', 'Lunge', NULL, '{}'::text[], ARRAY['Lunge','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Step Up', 'Quads', ARRAY['Glutes']::text[], 'Dumbbell', 'beginner', 'Lunge', 'Drive through the heel of the top foot. Don''t push off the bottom leg.', '{}'::text[], ARRAY['Lunge','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Deficit Reverse Lunge', 'Glutes', ARRAY['Quads']::text[], 'Dumbbell', 'advanced', 'Lunge', NULL, '{}'::text[], ARRAY['Lunge','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Split Squat', 'Quads', ARRAY['Glutes']::text[], 'Dumbbell', 'beginner', 'Lunge', NULL, '{}'::text[], ARRAY['Lunge','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Sissy Squat', 'Quads', '{}'::text[], 'Bodyweight', 'advanced', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Leg Extension', 'Quads', '{}'::text[], 'Machine', 'beginner', 'Isolation', 'Pause and squeeze at the top. This is the only movement that isolates the quads.', '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Single Leg Extension', 'Quads', '{}'::text[], 'Machine', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Wall Sit', 'Quads', '{}'::text[], 'Bodyweight', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Romanian Deadlift', 'Hamstrings', ARRAY['Glutes','Lower Back']::text[], 'Barbell', 'intermediate', 'Hinge', 'Push the hips back, soft knees. Stop when you feel the hamstrings, not when the bar hits the floor.', '{}'::text[], ARRAY['Hinge','Barbell']::text[], now()),
(gen_random_uuid(), 'Dumbbell Romanian Deadlift', 'Hamstrings', ARRAY['Glutes']::text[], 'Dumbbell', 'beginner', 'Hinge', NULL, '{}'::text[], ARRAY['Hinge','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Single Leg Romanian Deadlift', 'Hamstrings', ARRAY['Glutes','Core']::text[], 'Dumbbell', 'advanced', 'Hinge', NULL, '{}'::text[], ARRAY['Hinge','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Stiff Leg Deadlift', 'Hamstrings', ARRAY['Glutes','Lower Back']::text[], 'Barbell', 'advanced', 'Hinge', NULL, '{}'::text[], ARRAY['Hinge','Barbell']::text[], now()),
(gen_random_uuid(), 'Lying Leg Curl', 'Hamstrings', ARRAY['Calves']::text[], 'Machine', 'beginner', 'Isolation', 'Point the toes toward your shins to take the calves out of it.', '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Seated Leg Curl', 'Hamstrings', '{}'::text[], 'Machine', 'beginner', 'Isolation', 'Seated version stretches the hamstring more than lying. Slightly better for growth.', '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Standing Leg Curl', 'Hamstrings', '{}'::text[], 'Machine', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Nordic Curl', 'Hamstrings', '{}'::text[], 'Bodyweight', 'advanced', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Glute Ham Raise', 'Hamstrings', ARRAY['Glutes','Lower Back']::text[], 'Machine', 'advanced', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Cable Pull Through', 'Glutes', ARRAY['Hamstrings']::text[], 'Cable', 'beginner', 'Hinge', NULL, '{}'::text[], ARRAY['Hinge','Cable']::text[], now()),
(gen_random_uuid(), 'Barbell Hip Thrust', 'Glutes', ARRAY['Hamstrings']::text[], 'Barbell', 'intermediate', 'Hinge', 'Chin tucked, ribs down. Squeeze hard at the top for a full second.', '{}'::text[], ARRAY['Hinge','Barbell']::text[], now()),
(gen_random_uuid(), 'Machine Hip Thrust', 'Glutes', ARRAY['Hamstrings']::text[], 'Machine', 'beginner', 'Hinge', NULL, '{}'::text[], ARRAY['Hinge','Machine']::text[], now()),
(gen_random_uuid(), 'Single Leg Hip Thrust', 'Glutes', ARRAY['Hamstrings']::text[], 'Bodyweight', 'intermediate', 'Hinge', NULL, '{}'::text[], ARRAY['Hinge','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Glute Bridge', 'Glutes', ARRAY['Hamstrings']::text[], 'Bodyweight', 'beginner', 'Hinge', NULL, '{}'::text[], ARRAY['Hinge','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Cable Kickback', 'Glutes', '{}'::text[], 'Cable', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Machine Glute Kickback', 'Glutes', '{}'::text[], 'Machine', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Hip Abduction Machine', 'Glutes', '{}'::text[], 'Machine', 'beginner', 'Isolation', 'Lean forward slightly to bias the glute medius.', '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Hip Adduction Machine', 'Adductors', '{}'::text[], 'Machine', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Banded Lateral Walk', 'Glutes', '{}'::text[], 'Band', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Band']::text[], now()),
(gen_random_uuid(), 'Frog Pump', 'Glutes', '{}'::text[], 'Bodyweight', 'beginner', 'Hinge', NULL, '{}'::text[], ARRAY['Hinge','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Standing Calf Raise', 'Calves', '{}'::text[], 'Machine', 'beginner', 'Isolation', 'Full stretch at the bottom, full squeeze at the top. Slow it down.', '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Seated Calf Raise', 'Calves', '{}'::text[], 'Machine', 'beginner', 'Isolation', 'Bent knee hits the soleus, the muscle underneath the visible calf.', '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Smith Machine Calf Raise', 'Calves', '{}'::text[], 'Smith Machine', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Smith Machine']::text[], now()),
(gen_random_uuid(), 'Leg Press Calf Raise', 'Calves', '{}'::text[], 'Machine', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Single Leg Calf Raise', 'Calves', '{}'::text[], 'Bodyweight', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Donkey Calf Raise', 'Calves', '{}'::text[], 'Machine', 'intermediate', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Machine']::text[], now()),
(gen_random_uuid(), 'Tibialis Raise', 'Tibialis', '{}'::text[], 'Bodyweight', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Jump Squat', 'Quads', ARRAY['Glutes','Calves']::text[], 'Bodyweight', 'intermediate', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Pistol Squat', 'Quads', ARRAY['Glutes','Core']::text[], 'Bodyweight', 'advanced', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Cossack Squat', 'Adductors', ARRAY['Quads','Glutes']::text[], 'Bodyweight', 'intermediate', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Plank', 'Core', ARRAY['Shoulders']::text[], 'Bodyweight', 'beginner', 'Anti-Extension', 'Squeeze the glutes and tuck the ribs. A shaking 30 seconds beats a sagging 2 minutes.', '{}'::text[], ARRAY['Anti-Extension','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Side Plank', 'Obliques', ARRAY['Core']::text[], 'Bodyweight', 'beginner', 'Anti-Lateral Flexion', NULL, '{}'::text[], ARRAY['Anti-Lateral Flexion','Bodyweight']::text[], now()),
(gen_random_uuid(), 'RKC Plank', 'Core', '{}'::text[], 'Bodyweight', 'intermediate', 'Anti-Extension', NULL, '{}'::text[], ARRAY['Anti-Extension','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Dead Bug', 'Core', '{}'::text[], 'Bodyweight', 'beginner', 'Anti-Extension', 'Lower back stays flat on the floor the entire time.', '{}'::text[], ARRAY['Anti-Extension','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Bird Dog', 'Core', ARRAY['Lower Back','Glutes']::text[], 'Bodyweight', 'beginner', 'Anti-Rotation', NULL, '{}'::text[], ARRAY['Anti-Rotation','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Hanging Leg Raise', 'Abs', ARRAY['Hip Flexors']::text[], 'Bodyweight', 'advanced', 'Flexion', 'Curl the pelvis up at the top. Just lifting the legs is all hip flexor.', '{}'::text[], ARRAY['Flexion','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Hanging Knee Raise', 'Abs', ARRAY['Hip Flexors']::text[], 'Bodyweight', 'intermediate', 'Flexion', NULL, '{}'::text[], ARRAY['Flexion','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Captain''s Chair Knee Raise', 'Abs', '{}'::text[], 'Machine', 'beginner', 'Flexion', NULL, '{}'::text[], ARRAY['Flexion','Machine']::text[], now()),
(gen_random_uuid(), 'Toes to Bar', 'Abs', ARRAY['Lats']::text[], 'Bodyweight', 'advanced', 'Flexion', NULL, '{}'::text[], ARRAY['Flexion','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Cable Crunch', 'Abs', '{}'::text[], 'Cable', 'beginner', 'Flexion', 'Crunch the ribs toward the hips. Hips stay still, only the spine moves.', '{}'::text[], ARRAY['Flexion','Cable']::text[], now()),
(gen_random_uuid(), 'Machine Crunch', 'Abs', '{}'::text[], 'Machine', 'beginner', 'Flexion', NULL, '{}'::text[], ARRAY['Flexion','Machine']::text[], now()),
(gen_random_uuid(), 'Crunch', 'Abs', '{}'::text[], 'Bodyweight', 'beginner', 'Flexion', NULL, '{}'::text[], ARRAY['Flexion','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Sit Up', 'Abs', ARRAY['Hip Flexors']::text[], 'Bodyweight', 'beginner', 'Flexion', NULL, '{}'::text[], ARRAY['Flexion','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Decline Sit Up', 'Abs', '{}'::text[], 'Bodyweight', 'intermediate', 'Flexion', NULL, '{}'::text[], ARRAY['Flexion','Bodyweight']::text[], now()),
(gen_random_uuid(), 'V Up', 'Abs', '{}'::text[], 'Bodyweight', 'intermediate', 'Flexion', NULL, '{}'::text[], ARRAY['Flexion','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Reverse Crunch', 'Lower Abs', '{}'::text[], 'Bodyweight', 'beginner', 'Flexion', NULL, '{}'::text[], ARRAY['Flexion','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Ab Wheel Rollout', 'Core', ARRAY['Lats','Shoulders']::text[], 'Ab Wheel', 'advanced', 'Anti-Extension', 'Go only as far as you can without the lower back arching.', '{}'::text[], ARRAY['Anti-Extension','Ab Wheel']::text[], now()),
(gen_random_uuid(), 'Barbell Rollout', 'Core', ARRAY['Lats']::text[], 'Barbell', 'advanced', 'Anti-Extension', NULL, '{}'::text[], ARRAY['Anti-Extension','Barbell']::text[], now()),
(gen_random_uuid(), 'Pallof Press', 'Obliques', ARRAY['Core']::text[], 'Cable', 'beginner', 'Anti-Rotation', 'The whole point is resisting the twist. Don''t let the torso rotate at all.', '{}'::text[], ARRAY['Anti-Rotation','Cable']::text[], now()),
(gen_random_uuid(), 'Russian Twist', 'Obliques', ARRAY['Core']::text[], 'Plate', 'beginner', 'Rotation', NULL, '{}'::text[], ARRAY['Rotation','Plate']::text[], now()),
(gen_random_uuid(), 'Cable Woodchop', 'Obliques', ARRAY['Core']::text[], 'Cable', 'intermediate', 'Rotation', NULL, '{}'::text[], ARRAY['Rotation','Cable']::text[], now()),
(gen_random_uuid(), 'Landmine Rotation', 'Obliques', ARRAY['Core']::text[], 'Landmine', 'intermediate', 'Rotation', NULL, '{}'::text[], ARRAY['Rotation','Landmine']::text[], now()),
(gen_random_uuid(), 'Hollow Body Hold', 'Core', '{}'::text[], 'Bodyweight', 'intermediate', 'Anti-Extension', NULL, '{}'::text[], ARRAY['Anti-Extension','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Mountain Climber', 'Core', ARRAY['Shoulders']::text[], 'Bodyweight', 'beginner', 'Flexion', NULL, '{}'::text[], ARRAY['Flexion','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Bicycle Crunch', 'Obliques', ARRAY['Abs']::text[], 'Bodyweight', 'beginner', 'Rotation', NULL, '{}'::text[], ARRAY['Rotation','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Flutter Kick', 'Lower Abs', '{}'::text[], 'Bodyweight', 'beginner', 'Flexion', NULL, '{}'::text[], ARRAY['Flexion','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Suitcase Carry', 'Obliques', ARRAY['Forearms','Core']::text[], 'Dumbbell', 'beginner', 'Carry', NULL, '{}'::text[], ARRAY['Carry','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Side Bend', 'Obliques', '{}'::text[], 'Dumbbell', 'beginner', 'Lateral Flexion', NULL, '{}'::text[], ARRAY['Lateral Flexion','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Copenhagen Plank', 'Adductors', ARRAY['Core']::text[], 'Bodyweight', 'advanced', 'Anti-Lateral Flexion', NULL, '{}'::text[], ARRAY['Anti-Lateral Flexion','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Stir the Pot', 'Core', '{}'::text[], 'Stability Ball', 'advanced', 'Anti-Extension', NULL, '{}'::text[], ARRAY['Anti-Extension','Stability Ball']::text[], now()),
(gen_random_uuid(), 'Treadmill Walk (Incline)', 'Cardio', ARRAY['Calves','Glutes']::text[], 'Cardio Machine', 'beginner', 'Conditioning', '12 percent incline at 3mph is the sweet spot. Don''t hold the handles.', '{}'::text[], ARRAY['Conditioning','Cardio Machine']::text[], now()),
(gen_random_uuid(), 'Treadmill Run', 'Cardio', '{}'::text[], 'Cardio Machine', 'beginner', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning','Cardio Machine']::text[], now()),
(gen_random_uuid(), 'Stairmaster', 'Cardio', ARRAY['Glutes','Quads']::text[], 'Cardio Machine', 'beginner', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning','Cardio Machine']::text[], now()),
(gen_random_uuid(), 'Stationary Bike', 'Cardio', ARRAY['Quads']::text[], 'Cardio Machine', 'beginner', 'Conditioning', 'Zero impact, which is why it''s the go to when a joint is angry.', '{}'::text[], ARRAY['Conditioning','Cardio Machine']::text[], now()),
(gen_random_uuid(), 'Assault Bike', 'Cardio', ARRAY['Quads','Shoulders']::text[], 'Cardio Machine', 'intermediate', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning','Cardio Machine']::text[], now()),
(gen_random_uuid(), 'Rowing Machine', 'Cardio', ARRAY['Back','Legs']::text[], 'Cardio Machine', 'beginner', 'Conditioning', 'Legs, then back, then arms. Reverse that order on the way in.', '{}'::text[], ARRAY['Conditioning','Cardio Machine']::text[], now()),
(gen_random_uuid(), 'Elliptical', 'Cardio', '{}'::text[], 'Cardio Machine', 'beginner', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning','Cardio Machine']::text[], now()),
(gen_random_uuid(), 'Ski Erg', 'Cardio', ARRAY['Lats','Core']::text[], 'Cardio Machine', 'intermediate', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning','Cardio Machine']::text[], now()),
(gen_random_uuid(), 'Jump Rope', 'Cardio', ARRAY['Calves']::text[], 'Jump Rope', 'beginner', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning','Jump Rope']::text[], now()),
(gen_random_uuid(), 'Burpee', 'Cardio', ARRAY['Chest','Quads','Core']::text[], 'Bodyweight', 'intermediate', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Sled Push', 'Quads', ARRAY['Glutes','Calves']::text[], 'Sled', 'intermediate', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning','Sled']::text[], now()),
(gen_random_uuid(), 'Sled Drag', 'Hamstrings', ARRAY['Glutes']::text[], 'Sled', 'intermediate', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning','Sled']::text[], now()),
(gen_random_uuid(), 'Battle Ropes', 'Cardio', ARRAY['Shoulders','Core']::text[], 'Battle Ropes', 'intermediate', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning','Battle Ropes']::text[], now()),
(gen_random_uuid(), 'Kettlebell Swing', 'Glutes', ARRAY['Hamstrings','Core']::text[], 'Kettlebell', 'intermediate', 'Hinge', 'It''s a hip snap, not a squat and not a front raise. The arms are just rope.', '{}'::text[], ARRAY['Hinge','Kettlebell']::text[], now()),
(gen_random_uuid(), 'Box Jump', 'Quads', ARRAY['Glutes','Calves']::text[], 'Plyo Box', 'intermediate', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning','Plyo Box']::text[], now()),
(gen_random_uuid(), 'Outdoor Walk', 'Cardio', '{}'::text[], 'None', 'beginner', 'Conditioning', 'Steps are the most underrated fat loss tool there is.', '{}'::text[], ARRAY['Conditioning']::text[], now()),
(gen_random_uuid(), 'Incline Walk (Outdoor)', 'Cardio', ARRAY['Glutes','Calves']::text[], 'None', 'beginner', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning']::text[], now()),
(gen_random_uuid(), 'Swimming', 'Cardio', ARRAY['Lats','Shoulders']::text[], 'None', 'beginner', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning']::text[], now()),
(gen_random_uuid(), 'Power Clean', 'Full Body', ARRAY['Traps','Quads','Glutes']::text[], 'Barbell', 'advanced', 'Olympic', NULL, '{}'::text[], ARRAY['Olympic','Barbell']::text[], now()),
(gen_random_uuid(), 'Hang Clean', 'Full Body', ARRAY['Traps','Quads']::text[], 'Barbell', 'advanced', 'Olympic', NULL, '{}'::text[], ARRAY['Olympic','Barbell']::text[], now()),
(gen_random_uuid(), 'Clean and Jerk', 'Full Body', ARRAY['Shoulders','Quads']::text[], 'Barbell', 'advanced', 'Olympic', NULL, '{}'::text[], ARRAY['Olympic','Barbell']::text[], now()),
(gen_random_uuid(), 'Snatch', 'Full Body', ARRAY['Shoulders','Traps']::text[], 'Barbell', 'advanced', 'Olympic', NULL, '{}'::text[], ARRAY['Olympic','Barbell']::text[], now()),
(gen_random_uuid(), 'Thruster', 'Full Body', ARRAY['Quads','Shoulders']::text[], 'Barbell', 'advanced', 'Olympic', NULL, '{}'::text[], ARRAY['Olympic','Barbell']::text[], now()),
(gen_random_uuid(), 'Turkish Get Up', 'Full Body', ARRAY['Core','Shoulders']::text[], 'Kettlebell', 'advanced', 'Olympic', NULL, '{}'::text[], ARRAY['Olympic','Kettlebell']::text[], now()),
(gen_random_uuid(), 'Couch Stretch', 'Hip Flexors', ARRAY['Quads']::text[], 'Bodyweight', 'beginner', 'Mobility', NULL, '{}'::text[], ARRAY['Mobility','Bodyweight']::text[], now()),
(gen_random_uuid(), '90/90 Hip Stretch', 'Hips', '{}'::text[], 'Bodyweight', 'beginner', 'Mobility', NULL, '{}'::text[], ARRAY['Mobility','Bodyweight']::text[], now()),
(gen_random_uuid(), 'World''s Greatest Stretch', 'Full Body', ARRAY['Hips','Thoracic']::text[], 'Bodyweight', 'beginner', 'Mobility', NULL, '{}'::text[], ARRAY['Mobility','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Thoracic Extension on Foam Roller', 'Thoracic', '{}'::text[], 'Foam Roller', 'beginner', 'Mobility', NULL, '{}'::text[], ARRAY['Mobility','Foam Roller']::text[], now()),
(gen_random_uuid(), 'Cat Cow', 'Spine', '{}'::text[], 'Bodyweight', 'beginner', 'Mobility', NULL, '{}'::text[], ARRAY['Mobility','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Downward Dog', 'Hamstrings', ARRAY['Calves','Shoulders']::text[], 'Bodyweight', 'beginner', 'Mobility', NULL, '{}'::text[], ARRAY['Mobility','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Pigeon Pose', 'Glutes', ARRAY['Hips']::text[], 'Bodyweight', 'beginner', 'Mobility', NULL, '{}'::text[], ARRAY['Mobility','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Shoulder Dislocates', 'Shoulders', '{}'::text[], 'Band', 'beginner', 'Mobility', NULL, '{}'::text[], ARRAY['Mobility','Band']::text[], now()),
(gen_random_uuid(), 'Ankle Dorsiflexion Stretch', 'Ankles', ARRAY['Calves']::text[], 'Bodyweight', 'beginner', 'Mobility', 'Tight ankles are why a lot of people can''t squat deep.', '{}'::text[], ARRAY['Mobility','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Hamstring Stretch', 'Hamstrings', '{}'::text[], 'Bodyweight', 'beginner', 'Mobility', NULL, '{}'::text[], ARRAY['Mobility','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Child''s Pose', 'Lower Back', ARRAY['Lats']::text[], 'Bodyweight', 'beginner', 'Mobility', NULL, '{}'::text[], ARRAY['Mobility','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Foam Roll Quads', 'Quads', '{}'::text[], 'Foam Roller', 'beginner', 'Mobility', NULL, '{}'::text[], ARRAY['Mobility','Foam Roller']::text[], now()),
(gen_random_uuid(), 'Foam Roll IT Band', 'IT Band', '{}'::text[], 'Foam Roller', 'beginner', 'Mobility', NULL, '{}'::text[], ARRAY['Mobility','Foam Roller']::text[], now()),
(gen_random_uuid(), 'Foam Roll Upper Back', 'Thoracic', '{}'::text[], 'Foam Roller', 'beginner', 'Mobility', NULL, '{}'::text[], ARRAY['Mobility','Foam Roller']::text[], now()),
(gen_random_uuid(), 'Incline Cable Press', 'Upper Chest', ARRAY['Triceps']::text[], 'Cable', 'intermediate', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Cable']::text[], now()),
(gen_random_uuid(), 'Machine Fly', 'Chest', '{}'::text[], 'Machine', 'beginner', 'Horizontal Push', NULL, '{}'::text[], ARRAY['Horizontal Push','Machine']::text[], now()),
(gen_random_uuid(), 'Chest Supported T-Bar Row', 'Back', ARRAY['Biceps']::text[], 'Machine', 'beginner', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Machine']::text[], now()),
(gen_random_uuid(), 'Gorilla Row', 'Back', ARRAY['Biceps']::text[], 'Kettlebell', 'intermediate', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Kettlebell']::text[], now()),
(gen_random_uuid(), 'Renegade Row', 'Back', ARRAY['Core','Biceps']::text[], 'Dumbbell', 'advanced', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Barbell Overhead Carry', 'Shoulders', ARRAY['Core']::text[], 'Barbell', 'advanced', 'Carry', NULL, '{}'::text[], ARRAY['Carry','Barbell']::text[], now()),
(gen_random_uuid(), 'Dumbbell Overhead Carry', 'Shoulders', ARRAY['Core']::text[], 'Dumbbell', 'intermediate', 'Carry', NULL, '{}'::text[], ARRAY['Carry','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Cable Y Raise', 'Rear Delts', ARRAY['Traps']::text[], 'Cable', 'intermediate', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Machine Rear Delt Row', 'Rear Delts', ARRAY['Back']::text[], 'Machine', 'beginner', 'Horizontal Pull', NULL, '{}'::text[], ARRAY['Horizontal Pull','Machine']::text[], now()),
(gen_random_uuid(), 'Barbell Hack Squat', 'Quads', ARRAY['Glutes']::text[], 'Barbell', 'advanced', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Barbell']::text[], now()),
(gen_random_uuid(), 'Zercher Squat', 'Quads', ARRAY['Core','Glutes']::text[], 'Barbell', 'advanced', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Barbell']::text[], now()),
(gen_random_uuid(), 'Safety Bar Squat', 'Quads', ARRAY['Glutes','Upper Back']::text[], 'Specialty Bar', 'intermediate', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Specialty Bar']::text[], now()),
(gen_random_uuid(), 'Landmine Squat', 'Quads', ARRAY['Glutes']::text[], 'Landmine', 'beginner', 'Squat', NULL, '{}'::text[], ARRAY['Squat','Landmine']::text[], now()),
(gen_random_uuid(), 'Heels Elevated Goblet Squat', 'Quads', ARRAY['Glutes']::text[], 'Dumbbell', 'beginner', 'Squat', 'Elevating the heels lets you sit straighter and hammers the quads.', '{}'::text[], ARRAY['Squat','Dumbbell']::text[], now()),
(gen_random_uuid(), 'Reverse Nordic Curl', 'Quads', '{}'::text[], 'Bodyweight', 'advanced', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Banded Hamstring Curl', 'Hamstrings', '{}'::text[], 'Band', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Band']::text[], now()),
(gen_random_uuid(), 'Kettlebell Deadlift', 'Glutes', ARRAY['Hamstrings']::text[], 'Kettlebell', 'beginner', 'Hinge', NULL, '{}'::text[], ARRAY['Hinge','Kettlebell']::text[], now()),
(gen_random_uuid(), 'Barbell Glute Bridge', 'Glutes', ARRAY['Hamstrings']::text[], 'Barbell', 'beginner', 'Hinge', NULL, '{}'::text[], ARRAY['Hinge','Barbell']::text[], now()),
(gen_random_uuid(), 'Standing Cable Hip Abduction', 'Glutes', '{}'::text[], 'Cable', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Cable']::text[], now()),
(gen_random_uuid(), 'Seated Band Abduction', 'Glutes', '{}'::text[], 'Band', 'beginner', 'Isolation', NULL, '{}'::text[], ARRAY['Isolation','Band']::text[], now()),
(gen_random_uuid(), 'Weighted Plank', 'Core', '{}'::text[], 'Plate', 'intermediate', 'Anti-Extension', NULL, '{}'::text[], ARRAY['Anti-Extension','Plate']::text[], now()),
(gen_random_uuid(), 'Dragon Flag', 'Core', '{}'::text[], 'Bodyweight', 'advanced', 'Anti-Extension', NULL, '{}'::text[], ARRAY['Anti-Extension','Bodyweight']::text[], now()),
(gen_random_uuid(), 'Cable Pallof Rotation', 'Obliques', ARRAY['Core']::text[], 'Cable', 'intermediate', 'Rotation', NULL, '{}'::text[], ARRAY['Rotation','Cable']::text[], now()),
(gen_random_uuid(), 'Medicine Ball Slam', 'Core', ARRAY['Lats','Shoulders']::text[], 'Medicine Ball', 'beginner', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning','Medicine Ball']::text[], now()),
(gen_random_uuid(), 'Medicine Ball Rotational Throw', 'Obliques', ARRAY['Core']::text[], 'Medicine Ball', 'intermediate', 'Rotation', NULL, '{}'::text[], ARRAY['Rotation','Medicine Ball']::text[], now()),
(gen_random_uuid(), 'Sandbag Carry', 'Full Body', ARRAY['Core','Forearms']::text[], 'Sandbag', 'intermediate', 'Carry', NULL, '{}'::text[], ARRAY['Carry','Sandbag']::text[], now()),
(gen_random_uuid(), 'Prowler Sprint', 'Cardio', ARRAY['Quads','Glutes']::text[], 'Sled', 'advanced', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning','Sled']::text[], now()),
(gen_random_uuid(), 'Hill Sprint', 'Cardio', ARRAY['Hamstrings','Glutes']::text[], 'None', 'advanced', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning']::text[], now()),
(gen_random_uuid(), 'Shadow Boxing', 'Cardio', ARRAY['Shoulders','Core']::text[], 'None', 'beginner', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning']::text[], now()),
(gen_random_uuid(), 'Jumping Jacks', 'Cardio', '{}'::text[], 'Bodyweight', 'beginner', 'Conditioning', NULL, '{}'::text[], ARRAY['Conditioning','Bodyweight']::text[], now())
on conflict do nothing;