-- ARISE food library. Generated — see prisma/foods.py for the source table
-- and the 4/4/9 reconciliation check every non-alcohol row has to pass.
-- Safe to re-run: the delete only clears library rows, never a client's
-- own custom foods, and never anything a nutrition_log points at.

alter table public.foods add column if not exists category text;
alter table public.nutrition_logs add column if not exists name text;

delete from public.foods
 where source = 'library'
   and id not in (select food_id from public.nutrition_logs where food_id is not null);

insert into public.foods (id, name, source, calories, protein, carbs, fat, serving_size, category)
values
  (gen_random_uuid(), 'Chicken breast, grilled', 'library', 185, 35, 0, 4, '4 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Chicken breast, grilled', 'library', 280, 53, 0, 6, '6 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Chicken thigh, boneless skinless', 'library', 230, 27, 0, 13, '4 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Chicken thigh, bone-in with skin', 'library', 280, 24, 0, 20, '1 thigh', 'Protein'),
  (gen_random_uuid(), 'Chicken drumstick, roasted', 'library', 130, 14, 0, 8, '1 drumstick', 'Protein'),
  (gen_random_uuid(), 'Chicken drumstick, fried breaded', 'library', 195, 16, 6, 11, '1 drumstick', 'Protein'),
  (gen_random_uuid(), 'Chicken thigh, fried breaded', 'library', 280, 22, 9, 18, '1 thigh', 'Protein'),
  (gen_random_uuid(), 'Chicken wings, baked', 'library', 320, 30, 0, 22, '4 wings', 'Protein'),
  (gen_random_uuid(), 'Chicken tenderloin, grilled', 'library', 130, 26, 0, 3, '3 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Rotisserie chicken, white meat', 'library', 190, 33, 0, 6, '4 oz', 'Protein'),
  (gen_random_uuid(), 'Ground chicken, 93/7', 'library', 190, 30, 0, 8, '4 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Ground turkey, 93/7', 'library', 195, 31, 0, 8, '4 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Ground turkey, 99/1', 'library', 140, 32, 0, 2, '4 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Turkey breast, deli sliced', 'library', 90, 18, 2, 1, '3 oz', 'Protein'),
  (gen_random_uuid(), 'Turkey bacon', 'library', 70, 6, 1, 5, '2 slices', 'Protein'),
  (gen_random_uuid(), 'Ground beef, 90/10', 'library', 250, 30, 0, 14, '4 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Ground beef, 80/20', 'library', 300, 28, 0, 20, '4 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Ground beef, 96/4', 'library', 190, 31, 0, 7, '4 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Sirloin steak, grilled', 'library', 330, 46, 0, 15, '6 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Ribeye steak, grilled', 'library', 480, 42, 0, 34, '6 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Filet mignon, grilled', 'library', 350, 46, 0, 18, '6 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Flank steak, grilled', 'library', 320, 48, 0, 13, '6 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Beef pot roast, cooked', 'library', 350, 40, 0, 20, '5 oz', 'Protein'),
  (gen_random_uuid(), 'Beef stew meat, cooked', 'library', 250, 33, 0, 12, '4 oz', 'Protein'),
  (gen_random_uuid(), 'Pork chop, boneless grilled', 'library', 220, 34, 0, 9, '4 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Pork chop, thin flat-top cooked', 'library', 230, 26, 0, 13, '4 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Pork tenderloin, roasted', 'library', 165, 30, 0, 4, '4 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Pulled pork, no sauce', 'library', 280, 29, 0, 18, '4 oz', 'Protein'),
  (gen_random_uuid(), 'Bacon', 'library', 140, 10, 0, 11, '3 slices', 'Protein'),
  (gen_random_uuid(), 'Ham, deli sliced', 'library', 105, 16, 2, 4, '3 oz', 'Protein'),
  (gen_random_uuid(), 'Italian sausage link', 'library', 230, 13, 2, 19, '1 link', 'Protein'),
  (gen_random_uuid(), 'Hot dog, beef', 'library', 180, 7, 2, 16, '1 hot dog', 'Protein'),
  (gen_random_uuid(), 'Salmon, baked', 'library', 350, 39, 0, 21, '6 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Salmon, baked', 'library', 235, 26, 0, 14, '4 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Tilapia, baked', 'library', 195, 41, 0, 3, '6 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Cod, baked', 'library', 180, 39, 0, 2, '6 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Haddock, pan seared', 'library', 215, 38, 0, 6, '7 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Mahi mahi, grilled', 'library', 190, 41, 0, 2, '6 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Tuna, canned in water', 'library', 120, 27, 0, 1, '1 can (5 oz)', 'Protein'),
  (gen_random_uuid(), 'Tuna steak, seared', 'library', 250, 51, 0, 4, '6 oz cooked', 'Protein'),
  (gen_random_uuid(), 'Shrimp, cooked', 'library', 170, 36, 1, 2, '6 oz', 'Protein'),
  (gen_random_uuid(), 'Shrimp, breaded fried', 'library', 230, 12, 18, 12, '6 pieces', 'Protein'),
  (gen_random_uuid(), 'Sardines, canned in oil', 'library', 190, 23, 0, 11, '1 can', 'Protein'),
  (gen_random_uuid(), 'Scallops, seared', 'library', 160, 30, 5, 2, '6 oz', 'Protein'),
  (gen_random_uuid(), 'Egg, whole large', 'library', 70, 6, 1, 5, '1 egg', 'Protein'),
  (gen_random_uuid(), 'Eggs, whole large', 'library', 215, 19, 2, 15, '3 eggs', 'Protein'),
  (gen_random_uuid(), 'Eggs, whole large', 'library', 360, 32, 3, 24, '5 eggs', 'Protein'),
  (gen_random_uuid(), 'Egg whites', 'library', 125, 26, 2, 0, '1 cup', 'Protein'),
  (gen_random_uuid(), 'Egg white, single', 'library', 17, 4, 0, 0, '1 white', 'Protein'),
  (gen_random_uuid(), 'Greek yogurt, nonfat plain', 'library', 130, 23, 9, 0, '1 cup', 'Dairy'),
  (gen_random_uuid(), 'Greek yogurt, 2% plain', 'library', 160, 20, 9, 4, '1 cup', 'Dairy'),
  (gen_random_uuid(), 'Oikos Pro / high-protein yogurt cup', 'library', 140, 20, 9, 3, '1 cup', 'Dairy'),
  (gen_random_uuid(), 'Greek yogurt, flavored cup', 'library', 150, 15, 18, 2, '1 cup', 'Dairy'),
  (gen_random_uuid(), 'Cottage cheese, 2%', 'library', 190, 24, 9, 5, '1 cup', 'Dairy'),
  (gen_random_uuid(), 'Cottage cheese, 4%', 'library', 220, 25, 9, 10, '1 cup', 'Dairy'),
  (gen_random_uuid(), 'Milk, whole', 'library', 150, 8, 12, 8, '1 cup', 'Dairy'),
  (gen_random_uuid(), 'Milk, 2%', 'library', 120, 8, 12, 5, '1 cup', 'Dairy'),
  (gen_random_uuid(), 'Milk, skim', 'library', 85, 8, 12, 0, '1 cup', 'Dairy'),
  (gen_random_uuid(), 'Almond milk, unsweetened', 'library', 30, 1, 1, 3, '1 cup', 'Dairy'),
  (gen_random_uuid(), 'Oat milk', 'library', 120, 3, 16, 5, '1 cup', 'Dairy'),
  (gen_random_uuid(), 'Cheddar cheese', 'library', 115, 7, 1, 9, '1 oz', 'Dairy'),
  (gen_random_uuid(), 'Mozzarella, part skim', 'library', 85, 7, 1, 6, '1 oz', 'Dairy'),
  (gen_random_uuid(), 'Parmesan, grated', 'library', 45, 4, 0, 3, '2 tbsp', 'Dairy'),
  (gen_random_uuid(), 'String cheese', 'library', 80, 7, 1, 6, '1 stick', 'Dairy'),
  (gen_random_uuid(), 'Cream cheese', 'library', 100, 2, 2, 10, '2 tbsp', 'Dairy'),
  (gen_random_uuid(), 'Butter', 'library', 100, 0, 0, 11, '1 tbsp', 'Fats'),
  (gen_random_uuid(), 'Heavy cream', 'library', 100, 1, 1, 11, '2 tbsp', 'Dairy'),
  (gen_random_uuid(), 'Sour cream', 'library', 60, 1, 1, 5, '2 tbsp', 'Dairy'),
  (gen_random_uuid(), 'Whey protein powder', 'library', 120, 24, 3, 1, '1 scoop', 'Protein'),
  (gen_random_uuid(), 'Whey isolate powder', 'library', 110, 25, 1, 0, '1 scoop', 'Protein'),
  (gen_random_uuid(), 'Casein protein powder', 'library', 120, 24, 3, 1, '1 scoop', 'Protein'),
  (gen_random_uuid(), 'Plant protein powder', 'library', 130, 21, 5, 3, '1 scoop', 'Protein'),
  (gen_random_uuid(), 'Protein bar, typical', 'library', 210, 20, 22, 7, '1 bar', 'Protein'),
  (gen_random_uuid(), 'Protein shake, ready to drink', 'library', 160, 30, 5, 3, '1 bottle', 'Protein'),
  (gen_random_uuid(), 'Protein cookie', 'library', 280, 16, 32, 10, '1 cookie', 'Protein'),
  (gen_random_uuid(), 'White rice, cooked', 'library', 205, 4, 45, 0, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'White rice, cooked', 'library', 300, 6, 66, 1, '230 g', 'Carbs'),
  (gen_random_uuid(), 'Jasmine rice, cooked', 'library', 205, 4, 45, 0, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Brown rice, cooked', 'library', 215, 5, 45, 2, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Yellow rice, cooked', 'library', 240, 4, 47, 4, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Quinoa, cooked', 'library', 220, 8, 39, 4, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Oats, dry rolled', 'library', 150, 5, 27, 3, '1/2 cup', 'Carbs'),
  (gen_random_uuid(), 'Oatmeal, cooked with water', 'library', 160, 6, 28, 3, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Pasta, cooked', 'library', 220, 8, 43, 1, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Whole wheat pasta, cooked', 'library', 175, 8, 37, 1, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Bread, white', 'library', 80, 3, 15, 1, '1 slice', 'Carbs'),
  (gen_random_uuid(), 'Bread, whole wheat', 'library', 80, 4, 14, 1, '1 slice', 'Carbs'),
  (gen_random_uuid(), 'Sourdough bread', 'library', 100, 4, 20, 1, '1 slice', 'Carbs'),
  (gen_random_uuid(), 'Bagel, plain', 'library', 280, 11, 55, 2, '1 bagel', 'Carbs'),
  (gen_random_uuid(), 'English muffin', 'library', 130, 5, 25, 1, '1 muffin', 'Carbs'),
  (gen_random_uuid(), 'Tortilla, flour 8 inch', 'library', 150, 4, 24, 4, '1 tortilla', 'Carbs'),
  (gen_random_uuid(), 'Tortilla, corn 6 inch', 'library', 110, 3, 22, 1, '2 tortillas', 'Carbs'),
  (gen_random_uuid(), 'Potato, baked', 'library', 160, 4, 37, 0, '1 medium', 'Carbs'),
  (gen_random_uuid(), 'Potatoes, roasted', 'library', 230, 3, 25, 14, '140 g', 'Carbs'),
  (gen_random_uuid(), 'Baby potatoes, boiled', 'library', 180, 4, 40, 0, '6 small', 'Carbs'),
  (gen_random_uuid(), 'Sweet potato, baked', 'library', 115, 2, 27, 0, '1 medium', 'Carbs'),
  (gen_random_uuid(), 'French fries', 'library', 340, 4, 44, 16, 'medium order', 'Carbs'),
  (gen_random_uuid(), 'Home fries / oven wedges', 'library', 250, 4, 33, 11, '150 g', 'Carbs'),
  (gen_random_uuid(), 'Mashed potatoes with butter', 'library', 240, 4, 35, 9, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Cereal, o-shaped', 'library', 100, 3, 20, 2, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Granola', 'library', 230, 5, 34, 9, '1/2 cup', 'Carbs'),
  (gen_random_uuid(), 'Cream of wheat, cooked', 'library', 130, 4, 27, 0, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Couscous, cooked', 'library', 175, 6, 36, 0, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Corn on the cob', 'library', 80, 3, 17, 1, '1 ear', 'Carbs'),
  (gen_random_uuid(), 'Corn, kernels', 'library', 130, 5, 29, 2, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Rice cake', 'library', 35, 1, 7, 0, '1 cake', 'Carbs'),
  (gen_random_uuid(), 'Pancakes', 'library', 350, 8, 55, 11, '3 pancakes', 'Carbs'),
  (gen_random_uuid(), 'Waffle, frozen toasted', 'library', 190, 4, 30, 6, '2 waffles', 'Carbs'),
  (gen_random_uuid(), 'Black beans, cooked', 'library', 225, 15, 41, 1, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Pinto beans, cooked', 'library', 245, 15, 45, 1, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Refried beans', 'library', 220, 13, 36, 3, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Chickpeas, cooked', 'library', 270, 15, 45, 4, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Lentils, cooked', 'library', 230, 18, 40, 1, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Kidney beans, cooked', 'library', 220, 15, 40, 1, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Edamame, shelled', 'library', 190, 18, 14, 8, '1 cup', 'Carbs'),
  (gen_random_uuid(), 'Hummus', 'library', 70, 2, 6, 5, '2 tbsp', 'Fats'),
  (gen_random_uuid(), 'Olive oil', 'library', 120, 0, 0, 14, '1 tbsp', 'Fats'),
  (gen_random_uuid(), 'Avocado oil', 'library', 120, 0, 0, 14, '1 tbsp', 'Fats'),
  (gen_random_uuid(), 'Coconut oil', 'library', 120, 0, 0, 14, '1 tbsp', 'Fats'),
  (gen_random_uuid(), 'Cooking spray', 'library', 5, 0, 0, 1, '1 second', 'Fats'),
  (gen_random_uuid(), 'Peanut butter', 'library', 190, 8, 7, 16, '2 tbsp', 'Fats'),
  (gen_random_uuid(), 'Almond butter', 'library', 195, 7, 6, 18, '2 tbsp', 'Fats'),
  (gen_random_uuid(), 'Almonds', 'library', 165, 6, 6, 14, '1 oz', 'Fats'),
  (gen_random_uuid(), 'Walnuts', 'library', 185, 4, 4, 18, '1 oz', 'Fats'),
  (gen_random_uuid(), 'Cashews', 'library', 155, 5, 9, 12, '1 oz', 'Fats'),
  (gen_random_uuid(), 'Peanuts', 'library', 160, 7, 5, 14, '1 oz', 'Fats'),
  (gen_random_uuid(), 'Pistachios', 'library', 160, 6, 8, 13, '1 oz', 'Fats'),
  (gen_random_uuid(), 'Avocado', 'library', 160, 2, 9, 15, '1/2 medium', 'Fats'),
  (gen_random_uuid(), 'Guacamole', 'library', 50, 1, 3, 5, '2 tbsp', 'Fats'),
  (gen_random_uuid(), 'Chia seeds', 'library', 60, 2, 5, 4, '1 tbsp', 'Fats'),
  (gen_random_uuid(), 'Ground flaxseed', 'library', 55, 2, 3, 4, '1 tbsp', 'Fats'),
  (gen_random_uuid(), 'Mayonnaise', 'library', 95, 0, 0, 10, '1 tbsp', 'Fats'),
  (gen_random_uuid(), 'Light mayonnaise', 'library', 35, 0, 1, 3, '1 tbsp', 'Fats'),
  (gen_random_uuid(), 'Ranch dressing', 'library', 130, 1, 2, 13, '2 tbsp', 'Fats'),
  (gen_random_uuid(), 'Caesar dressing', 'library', 160, 1, 1, 17, '2 tbsp', 'Fats'),
  (gen_random_uuid(), 'Balsamic vinaigrette', 'library', 90, 0, 3, 8, '2 tbsp', 'Fats'),
  (gen_random_uuid(), 'Broccoli, cooked', 'library', 55, 4, 11, 1, '1 cup', 'Veg'),
  (gen_random_uuid(), 'Green beans, cooked', 'library', 45, 2, 10, 0, '1 cup', 'Veg'),
  (gen_random_uuid(), 'Asparagus, cooked', 'library', 40, 4, 7, 0, '1 cup', 'Veg'),
  (gen_random_uuid(), 'Spinach, raw', 'library', 15, 2, 2, 0, '2 cups', 'Veg'),
  (gen_random_uuid(), 'Spinach, cooked', 'library', 40, 5, 7, 0, '1 cup', 'Veg'),
  (gen_random_uuid(), 'Mixed greens salad, plain', 'library', 20, 2, 4, 0, '2 cups', 'Veg'),
  (gen_random_uuid(), 'Cabbage and carrot mix, cooked', 'library', 80, 3, 18, 0, '8 oz', 'Veg'),
  (gen_random_uuid(), 'Carrots, raw', 'library', 50, 1, 12, 0, '1 cup', 'Veg'),
  (gen_random_uuid(), 'Bell pepper', 'library', 30, 1, 7, 0, '1 medium', 'Veg'),
  (gen_random_uuid(), 'Onion, cooked', 'library', 45, 1, 10, 0, '1/2 cup', 'Veg'),
  (gen_random_uuid(), 'Mushrooms, cooked', 'library', 45, 3, 8, 1, '1 cup', 'Veg'),
  (gen_random_uuid(), 'Zucchini, cooked', 'library', 30, 2, 6, 0, '1 cup', 'Veg'),
  (gen_random_uuid(), 'Brussels sprouts, roasted', 'library', 95, 4, 12, 4, '1 cup', 'Veg'),
  (gen_random_uuid(), 'Cauliflower, cooked', 'library', 30, 2, 5, 0, '1 cup', 'Veg'),
  (gen_random_uuid(), 'Cauliflower rice', 'library', 25, 2, 5, 0, '1 cup', 'Veg'),
  (gen_random_uuid(), 'Tomato', 'library', 25, 1, 5, 0, '1 medium', 'Veg'),
  (gen_random_uuid(), 'Cucumber', 'library', 15, 1, 4, 0, '1 cup', 'Veg'),
  (gen_random_uuid(), 'Sweet corn salsa', 'library', 40, 1, 9, 0, '1/4 cup', 'Veg'),
  (gen_random_uuid(), 'Pico de gallo', 'library', 15, 1, 3, 0, '1/4 cup', 'Veg'),
  (gen_random_uuid(), 'Banana', 'library', 105, 1, 27, 0, '1 medium', 'Fruit'),
  (gen_random_uuid(), 'Apple', 'library', 95, 0, 25, 0, '1 medium', 'Fruit'),
  (gen_random_uuid(), 'Orange', 'library', 65, 1, 16, 0, '1 medium', 'Fruit'),
  (gen_random_uuid(), 'Strawberries', 'library', 50, 1, 12, 0, '1 cup', 'Fruit'),
  (gen_random_uuid(), 'Blueberries', 'library', 85, 1, 21, 0, '1 cup', 'Fruit'),
  (gen_random_uuid(), 'Raspberries', 'library', 65, 1, 15, 1, '1 cup', 'Fruit'),
  (gen_random_uuid(), 'Grapes', 'library', 105, 1, 27, 0, '1 cup', 'Fruit'),
  (gen_random_uuid(), 'Pineapple', 'library', 80, 1, 22, 0, '1 cup', 'Fruit'),
  (gen_random_uuid(), 'Watermelon', 'library', 45, 1, 11, 0, '1 cup', 'Fruit'),
  (gen_random_uuid(), 'Mango', 'library', 100, 1, 25, 0, '1 cup', 'Fruit'),
  (gen_random_uuid(), 'Peach', 'library', 60, 1, 14, 0, '1 medium', 'Fruit'),
  (gen_random_uuid(), 'Pear', 'library', 100, 1, 27, 0, '1 medium', 'Fruit'),
  (gen_random_uuid(), 'Cantaloupe', 'library', 55, 1, 13, 0, '1 cup', 'Fruit'),
  (gen_random_uuid(), 'Dates, medjool', 'library', 135, 1, 36, 0, '2 dates', 'Fruit'),
  (gen_random_uuid(), 'Raisins', 'library', 110, 1, 29, 0, '1/4 cup', 'Fruit'),
  (gen_random_uuid(), 'Applesauce, unsweetened', 'library', 100, 0, 27, 0, '1 cup', 'Fruit'),
  (gen_random_uuid(), 'Chicken burrito bowl, rice and beans', 'library', 700, 45, 78, 22, '1 bowl', 'Meals'),
  (gen_random_uuid(), 'Steak burrito bowl, rice and beans', 'library', 750, 45, 75, 28, '1 bowl', 'Meals'),
  (gen_random_uuid(), 'Burrito, beef rice and beans', 'library', 700, 35, 75, 28, '1 burrito', 'Meals'),
  (gen_random_uuid(), 'Chicken and rice bowl with veggies', 'library', 550, 45, 60, 12, '1 bowl', 'Meals'),
  (gen_random_uuid(), 'Grilled chicken salad, light dressing', 'library', 420, 40, 18, 20, '1 salad', 'Meals'),
  (gen_random_uuid(), 'Turkey sandwich on wheat', 'library', 380, 25, 45, 10, '1 sandwich', 'Meals'),
  (gen_random_uuid(), 'Grilled chicken sandwich', 'library', 440, 38, 43, 12, '1 sandwich', 'Meals'),
  (gen_random_uuid(), 'Fried chicken sandwich', 'library', 650, 32, 55, 33, '1 sandwich', 'Meals'),
  (gen_random_uuid(), 'Cheeseburger, quarter pound', 'library', 530, 30, 40, 27, '1 burger', 'Meals'),
  (gen_random_uuid(), 'Hamburger, single patty', 'library', 350, 20, 33, 15, '1 burger', 'Meals'),
  (gen_random_uuid(), 'Slider, beef', 'library', 230, 12, 20, 12, '1 slider', 'Meals'),
  (gen_random_uuid(), 'Pizza, cheese', 'library', 285, 12, 36, 10, '1 slice', 'Meals'),
  (gen_random_uuid(), 'Pizza, pepperoni', 'library', 315, 13, 36, 13, '1 slice', 'Meals'),
  (gen_random_uuid(), 'Sushi roll, salmon avocado', 'library', 350, 15, 50, 10, '8 pieces', 'Meals'),
  (gen_random_uuid(), 'Chicken stir fry with rice', 'library', 600, 40, 70, 16, '1 plate', 'Meals'),
  (gen_random_uuid(), 'Spaghetti with meat sauce', 'library', 600, 30, 75, 20, '1 plate', 'Meals'),
  (gen_random_uuid(), 'Chicken quesadilla', 'library', 650, 38, 45, 34, '1 whole', 'Meals'),
  (gen_random_uuid(), 'Beef tacos', 'library', 540, 27, 45, 27, '3 tacos', 'Meals'),
  (gen_random_uuid(), 'Chicken noodle soup', 'library', 110, 7, 15, 3, '1 cup', 'Meals'),
  (gen_random_uuid(), 'Chili with beef and beans', 'library', 290, 22, 25, 12, '1 cup', 'Meals'),
  (gen_random_uuid(), 'Protein oatmeal bowl', 'library', 420, 30, 50, 10, '1 bowl', 'Meals'),
  (gen_random_uuid(), 'Egg and cheese breakfast sandwich', 'library', 400, 20, 33, 21, '1 sandwich', 'Meals'),
  (gen_random_uuid(), 'Breakfast burrito, egg and sausage', 'library', 580, 26, 45, 32, '1 burrito', 'Meals'),
  (gen_random_uuid(), 'Caesar salad with chicken', 'library', 560, 40, 20, 35, '1 salad', 'Meals'),
  (gen_random_uuid(), 'Poke bowl, tuna and rice', 'library', 620, 38, 75, 18, '1 bowl', 'Meals'),
  (gen_random_uuid(), 'Beef jerky', 'library', 80, 12, 5, 1, '1 oz', 'Snacks'),
  (gen_random_uuid(), 'Pork rinds', 'library', 155, 17, 0, 9, '1 oz', 'Snacks'),
  (gen_random_uuid(), 'Popcorn, air popped', 'library', 95, 3, 19, 1, '3 cups', 'Snacks'),
  (gen_random_uuid(), 'Potato chips', 'library', 155, 2, 15, 10, '1 oz', 'Snacks'),
  (gen_random_uuid(), 'Tortilla chips', 'library', 140, 2, 19, 7, '1 oz', 'Snacks'),
  (gen_random_uuid(), 'Pretzels', 'library', 110, 3, 23, 1, '1 oz', 'Snacks'),
  (gen_random_uuid(), 'Crackers, saltine', 'library', 60, 1, 11, 1, '5 crackers', 'Snacks'),
  (gen_random_uuid(), 'Granola bar', 'library', 140, 3, 24, 4, '1 bar', 'Snacks'),
  (gen_random_uuid(), 'Trail mix', 'library', 175, 5, 16, 11, '1/4 cup', 'Snacks'),
  (gen_random_uuid(), 'Dark chocolate', 'library', 170, 2, 13, 12, '1 oz', 'Snacks'),
  (gen_random_uuid(), 'Milk chocolate bar', 'library', 215, 3, 24, 13, '1 bar', 'Snacks'),
  (gen_random_uuid(), 'Ice cream, vanilla', 'library', 140, 2, 16, 7, '1/2 cup', 'Snacks'),
  (gen_random_uuid(), 'Halo-style light ice cream', 'library', 100, 5, 16, 3, '1/2 cup', 'Snacks'),
  (gen_random_uuid(), 'Cookie, chocolate chip', 'library', 160, 2, 21, 8, '1 cookie', 'Snacks'),
  (gen_random_uuid(), 'Brownie', 'library', 240, 3, 36, 10, '1 square', 'Snacks'),
  (gen_random_uuid(), 'Donut, glazed', 'library', 260, 4, 31, 14, '1 donut', 'Snacks'),
  (gen_random_uuid(), 'Muffin, blueberry', 'library', 420, 6, 60, 18, '1 muffin', 'Snacks'),
  (gen_random_uuid(), 'Cinnamon roll', 'library', 340, 5, 51, 13, '1 roll', 'Snacks'),
  (gen_random_uuid(), 'Rice krispie treat', 'library', 90, 1, 18, 2, '1 bar', 'Snacks'),
  (gen_random_uuid(), 'Fruit snacks', 'library', 80, 0, 19, 0, '1 pouch', 'Snacks'),
  (gen_random_uuid(), 'Coffee, black', 'library', 5, 0, 0, 0, '1 cup', 'Drinks'),
  (gen_random_uuid(), 'Coffee with cream and sugar', 'library', 80, 1, 10, 4, '1 cup', 'Drinks'),
  (gen_random_uuid(), 'Latte, whole milk', 'library', 220, 12, 18, 11, '16 oz', 'Drinks'),
  (gen_random_uuid(), 'Latte, skim milk', 'library', 130, 13, 19, 0, '16 oz', 'Drinks'),
  (gen_random_uuid(), 'Espresso', 'library', 5, 0, 0, 0, '1 shot', 'Drinks'),
  (gen_random_uuid(), 'Orange juice', 'library', 110, 2, 26, 0, '1 cup', 'Drinks'),
  (gen_random_uuid(), 'Apple juice', 'library', 115, 0, 28, 0, '1 cup', 'Drinks'),
  (gen_random_uuid(), 'Soda, regular', 'library', 140, 0, 39, 0, '12 oz', 'Drinks'),
  (gen_random_uuid(), 'Diet soda', 'library', 0, 0, 0, 0, '12 oz', 'Drinks'),
  (gen_random_uuid(), 'Energy drink, sugar free', 'library', 10, 0, 2, 0, '12 oz', 'Drinks'),
  (gen_random_uuid(), 'Sports drink', 'library', 130, 0, 34, 0, '20 oz', 'Drinks'),
  (gen_random_uuid(), 'Beer, regular', 'library', 155, 2, 13, 0, '12 oz', 'Alcohol'),
  (gen_random_uuid(), 'Light beer', 'library', 105, 1, 6, 0, '12 oz', 'Alcohol'),
  (gen_random_uuid(), 'Wine, red', 'library', 125, 0, 4, 0, '5 oz', 'Alcohol'),
  (gen_random_uuid(), 'Wine, white', 'library', 120, 0, 4, 0, '5 oz', 'Alcohol'),
  (gen_random_uuid(), 'Seltzer, hard', 'library', 100, 0, 2, 0, '1 can', 'Alcohol'),
  (gen_random_uuid(), 'Liquor, 80 proof', 'library', 95, 0, 0, 0, '1.5 oz', 'Alcohol'),
  (gen_random_uuid(), 'Kombucha', 'library', 60, 0, 14, 0, '12 oz', 'Drinks'),
  (gen_random_uuid(), 'Smoothie, fruit and protein', 'library', 390, 30, 55, 6, '16 oz', 'Drinks'),
  (gen_random_uuid(), 'Ketchup', 'library', 20, 0, 5, 0, '1 tbsp', 'Condiments'),
  (gen_random_uuid(), 'Mustard', 'library', 5, 0, 1, 0, '1 tbsp', 'Condiments'),
  (gen_random_uuid(), 'BBQ sauce', 'library', 60, 0, 15, 0, '2 tbsp', 'Condiments'),
  (gen_random_uuid(), 'Hot sauce', 'library', 0, 0, 0, 0, '1 tsp', 'Condiments'),
  (gen_random_uuid(), 'Soy sauce', 'library', 10, 1, 1, 0, '1 tbsp', 'Condiments'),
  (gen_random_uuid(), 'Honey', 'library', 65, 0, 17, 0, '1 tbsp', 'Condiments'),
  (gen_random_uuid(), 'Maple syrup', 'library', 105, 0, 27, 0, '2 tbsp', 'Condiments'),
  (gen_random_uuid(), 'Sugar, granulated', 'library', 15, 0, 4, 0, '1 tsp', 'Condiments'),
  (gen_random_uuid(), 'Salsa', 'library', 10, 0, 2, 0, '2 tbsp', 'Condiments'),
  (gen_random_uuid(), 'Marinara sauce', 'library', 70, 2, 12, 2, '1/2 cup', 'Condiments'),
  (gen_random_uuid(), 'Buffalo sauce', 'library', 10, 0, 1, 1, '1 tbsp', 'Condiments'),
  (gen_random_uuid(), 'Sugar-free syrup', 'library', 15, 0, 4, 0, '2 tbsp', 'Condiments');
